{{- if and (eq .Values.storage.type "persistentVolumeClaim") (not .Values.storage.persistentVolumeClaim.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "telemetry-gen-and-send.fullname" . }}
  labels:
    {{- include "telemetry-gen-and-send.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.persistentVolumeClaim.accessMode }}
  {{- if .Values.storage.persistentVolumeClaim.storageClass }}
  storageClassName: {{ .Values.storage.persistentVolumeClaim.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistentVolumeClaim.size }}
{{- end }}
