{{- if not .Values.honeycomb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telemetry-gen-and-send.fullname" . }}
  labels:
    {{- include "telemetry-gen-and-send.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.honeycomb.apiKey | b64enc | quote }}
{{- end }}
